version: '3.4'

services:
  sourcingdb: 
    image: mongo


  esourcing.products:
    image: ${DOCKER_REGISTRY-}esourcingproducts
    build:
      context: .
      dockerfile: src/Services/Products/ESourcing.Products/Dockerfile

  esourcing.sourcing:
    image: ${DOCKER_REGISTRY-}esourcingsourcing
    build:
      context: .
      dockerfile: src/Services/Sourcing/ESourcing.Sourcing/Dockerfile

